# Numpy basics

In [2]:
import numpy as np
import time
from pylab import * # another way to import functions

### Benchmarking pure python vs numpy $\sum_{i=1}^N x_i * y_i$

In [3]:
lst_time_1 = []
for index in [10 ** i for i in range(1,7)]:
    x = range(1, index)
    y = range(1, index)
    acc = 0
    start = time.clock()
    for each_x, each_y in zip(x,y):
        acc += each_x * each_y
    end = time.clock()
    print acc
    # print end-start
    lst_time_1.append(end-start)

285
328350
332833500
333283335000
333328333350000
333332833333500000


In [4]:
lst_time_2 = []
for index in [10 ** i for i in range(1,7)]:
    x = np.arange(1, index)
    y = np.arange(1, index)
    start = time.clock()
    acc = np.dot(x,y)
    end = time.clock()
    print acc
    # print end-start
    lst_time_2.append(end-start)

285
328350
332833500
333283335000
333328333350000
333332833333500000


In [6]:
plot(range(1, len(lst_time_1) + 1), [x for x in lst_time_1], 'r-')
plot(range(1, len(lst_time_2) + 1), [x for x in lst_time_2], 'b-')
ylabel('time')
show()

In [12]:
example_array = np.array([1,2,3,4])
print example_array, type(example_array)
print example_array.shape
print example_array.size
print example_array[3]
print example_array[1:-1]


[1 2 3 4] <type 'numpy.ndarray'>
(4,)
4
4
[2 3]


In [8]:
a = np.arange(36).reshape(6,6)
print a

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [9]:
print a[2,2:4]
print a[0, 3:5]
print a[:,5]

[14 15]
[3 4]
[ 5 11 17 23 29 35]


In [10]:
print a.sum()
print a.sum(axis=0)
print a.sum(axis=1)
print a.sum(axis=-1)

630
[ 90  96 102 108 114 120]
[ 15  51  87 123 159 195]
[ 15  51  87 123 159 195]


In [11]:
print a == 5

[[False False False False False  True]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [12]:
print a <=20

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True False False False]
 [False False False False False False]
 [False False False False False False]]


In [14]:
print a
a[np.where(a<=25)] = 2000
print a

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[2000 2000 2000 2000 2000 2000]
 [2000 2000 2000 2000 2000 2000]
 [2000 2000 2000 2000 2000 2000]
 [2000 2000 2000 2000 2000 2000]
 [2000 2000   26   27   28   29]
 [  30   31   32   33   34   35]]


### Vectorize functions 

In [15]:

def sinc(x):
    if x == 0.0:
        return 1.0
    else:
        w = pi*x
    return sin(w) / w


print sinc([1.3,1.5])



TypeError: can't multiply sequence by non-int of type 'float'

In [16]:
vsinc = np.vectorize(sinc)
print vsinc([1.3,1.5])


[-0.19809085 -0.21220659]


In [18]:
x = r_[-5:5:100j]
print x
y = vsinc(x)
plot(x, y)
show()

[-5.         -4.8989899  -4.7979798  -4.6969697  -4.5959596  -4.49494949
 -4.39393939 -4.29292929 -4.19191919 -4.09090909 -3.98989899 -3.88888889
 -3.78787879 -3.68686869 -3.58585859 -3.48484848 -3.38383838 -3.28282828
 -3.18181818 -3.08080808 -2.97979798 -2.87878788 -2.77777778 -2.67676768
 -2.57575758 -2.47474747 -2.37373737 -2.27272727 -2.17171717 -2.07070707
 -1.96969697 -1.86868687 -1.76767677 -1.66666667 -1.56565657 -1.46464646
 -1.36363636 -1.26262626 -1.16161616 -1.06060606 -0.95959596 -0.85858586
 -0.75757576 -0.65656566 -0.55555556 -0.45454545 -0.35353535 -0.25252525
 -0.15151515 -0.05050505  0.05050505  0.15151515  0.25252525  0.35353535
  0.45454545  0.55555556  0.65656566  0.75757576  0.85858586  0.95959596
  1.06060606  1.16161616  1.26262626  1.36363636  1.46464646  1.56565657
  1.66666667  1.76767677  1.86868687  1.96969697  2.07070707  2.17171717
  2.27272727  2.37373737  2.47474747  2.57575758  2.67676768  2.77777778
  2.87878788  2.97979798  3.08080808  3.18181818  3